import ReactDOM from 'react-dom/client';
import Eight from './Components.js';
// import Printing from './printingInput.js';
// import React from 'react';
// import Login from './login.js';
// import Register from './register.js';
// import Tabsfunctionality from '../../mainproject1/src/ChangingTabs.js';
// import Datafetch from './datafetch.js';
// import FakeSourceApis from './fakesourceapis';
// import App from './hodtable.js';
// import Details from "./products&reviews.js";
import App from "./App.js";
var rootElement = document.getElementById('root');
var rootReference = ReactDOM.createRoot(rootElement);
// rootReference.render(<Car/>);
// rootReference.render(<Printing/>);
// rootReference.render(<Tabsfunctionality/>);
// rootReference.render(<Register/>);
// rootReference.render(<Datafetch/>);
// rootReference.render(<App/>);
rootReference.render(<App/>);
// rootReference.render(<Eight/>);